fixtures:
  repositories:
    stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    systemd: "git://github.com/camptocamp/puppet-systemd.git"
    apt: "git://github.com/puppetlabs/puppetlabs-apt.git"
    yumrepo_core:
      repo: https://github.com/puppetlabs/puppetlabs-yumrepo_core.git
      puppet_version: ">= 6.0.0"
