fixtures:
  repositories:
    stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    systemd: "git://github.com/camptocamp/puppet-systemd.git"
    apt: "git://github.com/puppetlabs/puppetlabs-apt.git"
