---
sudo: false
dist: trusty
language: ruby
cache: bundler
before_install:
  - bundle -v
  - rm Gemfile.lock || true
  - gem update --system
  - gem update bundler
  - gem --version
  - bundle -v
script:
  - 'bundle exec rake $CHECK'
matrix:
  fast_finish: true
  include:
  - rvm: 2.4.2
    bundler_args: --without development release
    dist: trusty
    env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_set=docker/ubuntu-14.04 CHECK=beaker
    services: docker
    sudo: required
  - rvm: 2.4.2
    bundler_args: --without development release
    dist: trusty
    env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_set=docker/ubuntu-16.04 CHECK=beaker
    services: docker
    sudo: required
  - rvm: 2.4.2
    bundler_args: --without development release
    dist: trusty
    env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_set=docker/centos-6 CHECK=beaker
    services: docker
    sudo: required
  - rvm: 2.4.2
    bundler_args: --without development release
    dist: trusty
    env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_set=docker/centos-7 CHECK=beaker
    services: docker
    sudo: required
  - rvm: 2.4.2
    bundler_args: --without development release
    dist: trusty
    env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_set=docker/debian-8 CHECK=beaker
    services: docker
    sudo: required
  - rvm: 2.1.9
    bundler_args: --without system_tests development release
    env: PUPPET_VERSION="~> 4.0" CHECK=test PARALLEL_TEST_PROCESSORS=16
  - rvm: 2.4.2
    bundler_args: --without system_tests development release
    env: PUPPET_VERSION="~> 5.0" CHECK=test_with_coveralls
  - rvm: 2.4.2
    bundler_args: --without system_tests development release
    env: PUPPET_VERSION="~> 5.0" CHECK=rubocop
  - rvm: 2.4.2
    bundler_args: --without system_tests development release
    env: PUPPET_VERSION="~> 5.0" CHECK=build DEPLOY_TO_FORGE=yes
branches:
  only:
  - master
  - /^v\d/
notifications:
  email: false
  irc:
    on_success: always
    on_failure: always
    channels:
      - "chat.freenode.org#voxpupuli-notifications"
deploy:
  provider: puppetforge
  user: puppet
  password:
    secure: "k2eyprVmf+1ouw86/4rhyQ/j/cf/uJly5Gww282NibxexQLqEgWwqm0ivgADv6T952J6n6AHAHhtAAq+PZ6NEUfGjM0vl99EH44Le92dp4b2EwW35kbbs7pfmnLMnyt5A6mLevUAcTmMZHKXAcS/8VWHx9elahm1o9d2VU0Vl+sEbdisPPK76nqa1G9BaTlSud7AEl3PT09HMyMDeYJBRU8S1I3vVckEulK+MMEeMwTNFaUtdnHSSo1Ky6DaoRTOFaioz187QTzcIvYnARjYiNwo/ucvekFcCAZXmym4Xhz3UlUTm+Gjf4tXHUD2UoI09Vs6Cz+0lhN90tNJvIiz4D1qNMfFSoQzGm+1eG/sAsmWzdBSggC/EBPPPqT4TTLV0fsmUZwUGgpqQGU0XripMLEPmhdeAbH9o1oprUGuNSPXtrjO1nA0U1gWbrC2w9ko2y00YOFxGEL11uKvQyeWTL2WFIy/FvqxJvg1lkA+AU8+DfWKhKcE7lmFqsqAYyknHQ1H33AeSIlD4xg3foCRQh6XpTdxnHrus5iT9xuAkv45TvwiU+jH+K0mTNi6E1XzFL9GizyQprkpE14wQAwTEgdvi3LRaeNxlkzLUgrbQhWEyIiwGtB9tbCoZiLrMQw2LdNTrz0iS23KPh85gF2YlsxDYYA5TmSdzSiwkEEDl9U="
  on:
    tags: true
    # all_branches is required to use tags
    all_branches: true
    # Only publish the build marked with "DEPLOY_TO_FORGE"
    condition: "$DEPLOY_TO_FORGE = yes"
